sudo: required

language: php

services:
  - docker

before_install:
  - docker pull php:5.6-apache
  - docker run -d -p 127.0.0.1:80:4567 php:5.6-apache /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"

script:
  - bundle exec rake test
